[jype_recruit]
title = "JYP RECRUIT"
url = "https://recruit.jype.com/Recruit"
entrySelector = "div.recruitList ul li"
titleSelector = "strong.tit"
linkSelector = "a"
contentSelector = "span.date"
waitUntil = "networkidle"

[sm_recruit]
title = "SM Entertainment ─ RECRUIT"
url = "https://recruit.smentertainment.com/"
entrySelector = "ul.hrlist li"
titleSelector = "span.title_txt"
linkSelector = "a"
contentSelector = "div.sts p"
waitUntil = "networkidle"

[yg_recruit]
title = "YG Entertainment ─ RECRUIT"
url = "https://yg-entertainment.recruiter.co.kr/app/jobnotice/list"
entrySelector = "div.list-bbs with-tab ul li"
titleSelector = "h2.list-bbs-title"
linkSelector = "span.list-bbs-notice-name a"
contentSelector = "span.list-bbs-date"
waitUntil = "networkidle"

[vlive_onstage]
title = "ONSTAGE (온스테이지)"
url = "https://www.vlive.tv/channel/E61323/board/4268?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"

[vlive_smtown]
title = "SMTOWN ─ Media Board"
url = "https://vlive.tv/channel/FD53B/board/3530"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[vlive_smtown_notice]
title = "SMTOWN ─ Media Board"
url = "https://www.vlive.tv/channel/FD53B/board/69"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[flo_newtrack]
title = "FLO ─ New Track"
url = "https://www.music-flo.com/new/track?sortType=KPOP"
entrySelector = "div.section_content_wrap > table > tbody > tr"
titleSelector = "div.txt_area > button > p > strong"
linkSelector = "div.txt_area > a"
imageSelector = "div a img[src^='https://cdn.music-flo.com/image/v2/album/']"
contentSelector = "span.artist_link_w > span > span:nth-child(1) > a"
waitUntil = "networkidle"

[flo_newalbum]
title = "FLO ─ New Album"
url = "https://www.music-flo.com/new/album?sortType=KPOP"
entrySelector = "ul.thumbnail_list.badge_thumbnail_list li"
titleSelector = "p.title a"
linkSelector = "a"
imageSelector = "div[class='album_thumbnail'] a img"
contentSelector = "p.artist"
waitUntil = "networkidle"

[kindiechart]
title = "K-INDIE CHART"
url = "http://mirrorballmusic.co.kr/k-indie-chart/"
entrySelector = "div[class='category-post-list'] article"
titleSelector = "h1[class='post-title blue']"
linkSelector = "div a[class='btn-view-chart']"
imageSelector = "div[class='post-thumb'] img"
contentSelector = "h2[class='sub-title']"
waitUntil = "networkidle"
onFail = "stale"
