[vlive_smtown]
title = "SMTOWN ─ Media Board"
url = "https://vlive.tv/channel/FD53B/board/3530"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[vlive_smtown_notice]
title = "SMTOWN ─ Media Board"
url = "https://www.vlive.tv/channel/FD53B/board/69"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[flo_newtrack]
title = "FLO ─ New Track"
url = "https://www.music-flo.com/new/track?sortType=KPOP"
entrySelector = "div.section_content_wrap > table > tbody > tr"
titleSelector = "div.txt_area > button > p > strong"
linkSelector = "div.txt_area > a"
imageSelector = "div a img[src^='https://cdn.music-flo.com/image/v2/album/']"
contentSelector = "span.artist_link_w > span > span:nth-child(1) > a"
waitUntil = "networkidle"

[flo_newalbum]
title = "FLO ─ New Album"
url = "https://www.music-flo.com/new/album?sortType=KPOP"
entrySelector = "ul.thumbnail_list.badge_thumbnail_list li"
titleSelector = "p.title a"
linkSelector = "a"
imageSelector = "div[class='album_thumbnail'] a img"
contentSelector = "p.artist"
waitUntil = "networkidle"

[kindiechart]
title = "K-INDIE CHART"
url = "http://mirrorballmusic.co.kr/k-indie-chart/"
entrySelector = "div[class='category-post-list'] article"
titleSelector = "h1[class='post-title blue']"
linkSelector = "div a[class='btn-view-chart']"
imageSelector = "div[class='post-thumb'] img"
contentSelector = "h2[class='sub-title']"
waitUntil = "networkidle"
onFail = "stale"
